### PR TITLE
Added reverse engineered PCB files

### PR DESCRIPTION
**Pull request by Kenagon**
Added reverse engineered PCB files (Gerbers, BOM)

### CODE REVIEW

**Comment by raleighlittles** [comment]
@Kenagon do you have the centroid file? I placed an order through PCB Way using the gerber file zip but for assembly they're asking for the Centroid file.

**Comment by Kenagon** [comment]
@raleighlittles  try this, if everything is ok, I'll add it to the PR [PickAndPlace_PCB_BBL.xlsx](https://github.com/user-attachments/files/16828211/PickAndPlace_PCB_BBL.xlsx)

**Comment by raleighlittles** [comment]
@Kenagon thanks, I provided that to them! They did have a follow-up question during the assembly process.

One was basically about a mismatch in the part numbers on the resistor used, between the BOM and the design [?] 

image

Also that resistor was marked as "NA", which just to clarify, means it shouldn't be populated on the board right? I assumed the answer was yes but just wanted to clarify.

**Comment by Kenagon** [comment]
R14, R17, C27, C29 should not be populated

**Comment by raleighlittles** [comment]
The boards from PCBWay came in!
IMG_5538
IMG_5537

**Comment by Kenagon** [comment]
they look great

**Review by thekakester — APPROVED** [review]

**Pull request merged**
